name: Deployment to Heroku

on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: 3/3.1/phonebook/backend
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "3/3.1/phonebook/backend"
          usedocker: true
          dontuseforce: false
