version: '3.8'

services:

    simple-web-service-ubuntu:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes:
        - .:/usr/src/app
      container_name: simple-web-service