FROM ubuntu:18.04

#FROM golang:1.17.2-alpine

RUN apt-get update && apt-get install -y wget gcc && rm -rf /usr/local/go && wget -c https://golang.org/dl/go1.17.2.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz

#RUN apk update && apk upgrade && apk add --no-cache gcc libc-dev

COPY . .

ENV PATH=$PATH:/usr/local/go/bin

RUN go get -v -d ./

#RUN go get -v -d ./...

RUN useradd -m nonroot

#RUN addgroup -S nonroot

#RUN adduser -S -D -h /app nonroot nonroot

#COPY . .

#RUN chmod a+rx -R ./ && chown nonroot:nonroot -R ./ && chown nonroot:nonroot /app

ENV PORT=8080

ENV REQUEST_ORIGIN=http://localhost:5000

ENV SECRET=secret

ENV CHOKIDAR_USEPOLLING=true

RUN go build -v -o ./server

RUN chmod a+x ./server && chown nonroot:nonroot ./server

#USER nonroot:nonroot

EXPOSE 8080

#ENV PATH=$PATH:/usr/local/bin/server

RUN echo $PATH && pwd && ls -l ./server && ls -l .

CMD "/bin/sh -c ./server"