FROM node:16 as build

WORKDIR /usr/src/app/

COPY package*.json ./

ENV NODE_ENV=production

RUN npm install

COPY . ./

FROM node:16.3.0-alpine

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup -h /bin/sh -D appuser && chown appuser:appgroup -R /usr/src/app && chmod a+rx -R /usr/src/app

USER appuser

ENTRYPOINT ["npm", "start", "--port", "3001"]