version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - FRONTEND_CONNECTION_URL=frontend:5000
      - BACKEND_CONNECTION_URL=backend:8080
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./files:data
  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    image: backend
    container_name: backend
    build: backend/.
    ports:
      - 8000:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      REQUEST_ORIGIN: http://localhost:5000
    depends_on:
      - redis
      - db
  frontend:
    image: frontend
    container_name: frontend
    build: frontend/.
    ports:
      - 5000:5000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000