name: Deployment to Heroku

on:
  push:
    branches:
      - 'main'
defaults:
  run:
    working-directory: 3/3.1/phonebook/backend
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Login to Heroku"
        run: heroku container:login
      - name: Build and Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPLICATION_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
          appdir: "."
          usedocker: true
          justlogin: true
      - name: "Login to Heroku"
        run: heroku container:login
      - name: "Build and Push to Heroku"
        run: heroku container:push web --app ${{secrets.HEROKU_APPLICATION_NAME}}
      - name: "Release"
        run: heroku container:release web --app ${{secrets.HEROKU_APPLICATION_NAME}}
