name: Deployment to Heroku

on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: 3/3.1/phonebook/backend
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Build, Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APPLICATION_NAME: ${{ secrets.HEROKU_APPLICATION_NAME }}
          HEROKU_EMAIL_ADDRESS: ${{ secrets.HEROKU_EMAIL_ADDRESS }}
        run: heroku container:push -a $HEROKU_APPLICATION_NAME web 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APPLICATION_NAME: ${{ secrets.HEROKU_APPLICATION_NAME }}
        run: heroku container:release -a $HEROKU_APPLICATION_NAME web 
